name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: 
          - { name: gcc, cxx: g++-14 }
          - { name: clang, cxx: clang++-20 }

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          cmake \
          ninja-build \
          gcc-14 \
          g++-14 \
          clang-20 \
          libblas-dev \
          liblapack-dev \
          libgtest-dev

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure
